apiVersion: v1
kind: Pod
metadata:
  name: app	
  labels:
    name: app
spec:
  containers:
  - name: app
    image: app1:$BUILD_ID
    ports:
    - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: app
  labels:
    app: app
spec:
  ports:
  - port: 8080
    targetPort: 4000
  type: NodePort
  selector:
    app: app

